### ISSUE TITLE
Error: map error: failed to create map `OUTPUT_BUF` with code -1

### ISSUE THREAD

**Issue by df13954** [ri-char/eStrace#1]
pixel6,android13,
kernel 5.10.149

```

oriole:/data/local/tmp # ./estrace-aarch64-linux-android --uid 10249
Error: map error: failed to create map `OUTPUT_BUF` with code -1

Caused by:
    0: failed to create map `OUTPUT_BUF` with code -1
    1: Operation not permitted (os error 1)
oriole:/data/local/tmp #
```

**Comment by tiann** [comment]
```
oriole:/ # ulimit -l
64
```

This value is too small on some devices.

**Comment by tiann** [comment]
[estrace.zip](https://github.com/ri-char/eStrace/files/11755358/estrace.zip)

Try my build to check if if works.

**Comment by df13954** [comment]
> [estrace.zip](https://github.com/ri-char/eStrace/files/11755358/estrace.zip)
> 
> Try my build to check if if works.

Okay！！！thanks！

**Comment by df13954** [comment]
> I haven't tested on kernel 5.10. It works well on 5.15.
> 
> Please use the following command to check the kernel parameter and make sure that BPF is enable.
> 
> ```shell
> zcat /proc/config.gz | grep BPF
> ```
> 
> Here is mine: ![Screenshot_2023-06-15-16-26-12-959_com.termux-edit.jpg](https://user-images.githubusercontent.com/17962023/246044601-03964980-61df-4246-a14d-41750a88e5b6.jpg)

<img width="915" alt="Xnip2023-06-16_17-16-18" src="https://github.com/ri-char/eStrace/assets/18607031/cbd18c9d-41a3-40a3-bfad-2ebac069c266">
