### ISSUE TITLE
Run command is not working

### ISSUE THREAD

**Issue by UdayakumarHidakal** [ri-char/eStrace#7]
While running the existing example, we are getting some errors.

**Errors description :** 

```hqd1kor@KOR-V-000MK:~/devspace/eStrace$ cargo xtask run -- -f all
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/xtask run -- -f all`
    Finished dev [optimized] target(s) in 0.04s
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
The result is at target/x86_64-unknown-linux-musl/debug/estrace
error: the following required arguments were not provided:
  <--pid <PID>|--tid <TID>|--uid <UID>>

Usage: estrace --filter <FILTER> <--pid <PID>|--tid <TID>|--uid <UID>>

For more information, try '--help'.
```

 can't we run without `pid` `tid` & `uid`?

**Comment by ri-char** [comment]
Allowing without constraints can lead to the generation of a large number of messages. This is because the process of reading messages from `bpf` to outputing also generates many system calls, which in turn are trapped. This eventually leads to a crash.

**Comment by UdayakumarHidakal** [comment]
can you please give me the example command which is running process `cargo xtask run -- -f %process --pid` ,
then what we need to pass after `--pid` exciting process pid's or listed pid's

**Comment by ri-char** [comment]
try 867227b

**Comment by rolemee** [comment]
I have the same problems,does it solved?
