### ISSUE TITLE
运行失败：Error: error relocating function

### ISSUE THREAD

**Issue by yujack008** [ri-char/eStrace#8]
运行提示如下：
blueline:/data/local/tmp # ./estrace -p 3700
Error: error relocating function

Caused by:
    0: error relocating `enter_syscall`
    1: section `5` not found, referenced by symbol `` #52
blueline:/data/local/tmp #

内核版本：
blueline:/data/local/tmp # uname -a
Linux localhost 4.9.185-g2def8b88165c-ab5921089 #0 SMP PREEMPT Fri Oct 4 20:58:55 UTC 2019 aarch64

手机：Android 10系统。

**Comment by ri-char** [comment]
不支持内核版本小于5.10的系统

**Comment by yujack008** [comment]
> 不支持内核版本小于5.10的系统

你好，是什么原因导致不支持呢，是aya不支持，还是android内核不支持呢，看aya官方也没有说需要5.10以上内核版本。
还有5.10以上内核版本是安卓几呢。
非常感谢！

**Comment by ri-char** [comment]
内核版本4.9有较多ebpf特性不支持，实现比较困难，如果你可以实现，欢迎提交pr。
内核版本和android版本没有直接联系，一般来说同一个设备不同rom的内核版本都是一样或相近的。如果想要提高内核版本，建议更换设备。
